import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';

import {
  DxMenuModule,
  DxTextBoxModule,
  DxValidatorModule,
  DxButtonModule,
  DxLoadPanelModule,
  DxDropDownBoxModule,
  DxDataGridModule,
  DxPopupModule,
  DxCheckBoxModule,
  DxDateBoxModule,
  DxSelectBoxModule,
  DxTextAreaModule,
  DxTooltipModule,
  DxFileUploaderModule,
  DxSchedulerModule,
  DxFormModule,
  DxValidationSummaryModule,
  DxTagBoxModule,
  DxFilterBuilderModule,
  DxTreeListModule,
  DxSwitchModule,
  DxNumberBoxModule,
  DxTabPanelModule,
  DxRadioGroupModule,
  DxAccordionModule,
  DxLoadIndicatorModule,
} from 'devextreme-angular';

@NgModule({
  declarations: [],
  imports: [],
  exports: [
    FormsModule,
    DxMenuModule,
    DxTextBoxModule,
    DxValidatorModule,
    DxButtonModule,
    DxLoadPanelModule,
    DxDropDownBoxModule,
    DxDataGridModule,
    DxPopupModule,
    DxCheckBoxModule,
    DxDateBoxModule,
    DxSelectBoxModule,
    DxTextAreaModule,
    DxTooltipModule,
    DxFileUploaderModule,
    DxSchedulerModule,
    DxFormModule,
    DxValidationSummaryModule,
    DxTagBoxModule,
    DxFilterBuilderModule,
    DxTreeListModule,
    DxSwitchModule,
    DxNumberBoxModule,
    DxTabPanelModule,
    DxRadioGroupModule,
    DxAccordionModule,
    DxLoadIndicatorModule,
  ],
})
export class DevExtremeModule {}
